theme: jekyll-theme-minimal
title: Bergey Lab Guidelines and Tips
description: Guidelines and tips for members of the Bergey Lab (Christina Bergey - www.bergey-lab.org)
logo: https://github.com/bergeylab/bergey-lab-guidelines/raw/gh-pages/Bergey_just_mosquito.png
